fastlane_version "2.68.2"

default_platform :android

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Upload Android extensions"
  lane :release_android_extension do
    gradle(task: "clean")
    gradle(task: ":android-extension:install")
    gradle(task: ":android-extension:bintrayUpload")
  end

  desc "Upload Rx Extensions"
  lane :release_rx_extension do
    gradle(task: "clean")
    gradle(task: ":rx-extension:install")
    gradle(task: ":rx-extension:bintrayUpload")
  end

  desc "Deploy all libs to maven"
  lane :deploy do
    release_android_extension
    release_rx_extension
  end
end
